#!/usr/bin/env bash
set -euo pipefail

# Created for artifact reviewers: build the trace manifest from DLIO output
# directories generated by the reviewer-run sweep.

REPRO_ROOT="${REPRO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
GLOBALS_DIR="${GLOBALS_DIR:-$REPRO_ROOT/globals}"
TRACE_ROOT="${TRACE_ROOT:-/p/lustre3/${USER}/dlio-benchmark-output}"
TRACE_PATTERN="${TRACE_PATTERN:-train_*}"
CSV_FILE="${1:-${CSV_FILE:-$GLOBALS_DIR/trace_paths.csv}}"

if command -v python >/dev/null 2>&1; then
    PYTHON_BIN="python"
elif command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="python3"
else
    printf 'No python interpreter found on PATH.\n' >&2
    exit 1
fi

mkdir -p "$GLOBALS_DIR"

printf 'version,workload_name,num_nodes,ci_date,trace_path,trace_size_bytes,trace_size_fmt\n' >"$CSV_FILE"

find "$TRACE_ROOT" -mindepth 2 -maxdepth 2 -type d -name "$TRACE_PATTERN" | sort | while IFS= read -r trace_path; do
    output_json="$trace_path/0_output.json"
    config_json=""
    for candidate in "$trace_path/config.json" "$trace_path/run_config.json"; do
        if [[ -f "$candidate" ]]; then
            config_json="$candidate"
            break
        fi
    done
    if [[ -z "$config_json" || ! -f "$output_json" ]]; then
        printf 'Skipping incomplete trace directory: %s\n' "$trace_path" >&2
        continue
    fi
    workload_name="$(basename "$(dirname "$trace_path")")"
    trace_dir_name="$(basename "$trace_path")"
    ci_date="${trace_dir_name#train_}"
    ci_date="${ci_date//_/}"
    node_num="$("$PYTHON_BIN" - "$config_json" <<'PY'
import json
import sys
with open(sys.argv[1]) as fh:
    print(json.load(fh)["num_nodes"])
PY
)"
    size_bytes="$(du -sb "$trace_path" | cut -f1)"
    size_formatted="$(du -sh "$trace_path" | cut -f1)"
    printf 'custom,%s,%s,%s,%s,%s,%s\n' "$workload_name" "$node_num" "$ci_date" "$trace_path" "$size_bytes" "$size_formatted" >>"$CSV_FILE"
done

printf 'Trace manifest written to %s\n' "$CSV_FILE"
